import makeWASocket, { DisconnectReason, useMultiFileAuthState, fetchLatestBaileysVersion } from 'baileys'; import QRCode from 'qrcode'; import { Boom } from '@hapi/boom'; import pino from 'pino'; import fs from 'node:fs/promises'; import { config } from '../config/config.js'; import { logger } from './logger.js';
let sock=null, state={status:'starting',qr:null,pairingCode:null,lastError:null}; let starting=false;
export const connectionState=()=>({...state,connected:Boolean(sock?.user),user:sock?.user?.id||null});
export async function startConnection(){ if(starting||sock) return sock; starting=true; state={...state,status:'connecting',qr:null,pairingCode:null}; await fs.mkdir(config.authDir,{recursive:true}); const {state:auth,saveCreds}=await useMultiFileAuthState(config.authDir); let version; try { ({version}=await fetchLatestBaileysVersion()); } catch { version=[2,3000,1015901307]; }
 sock=makeWASocket({version,auth,printQRInTerminal:false,logger:pino({level:'silent'}),browser:['HASEEB-MD','Chrome','1.0.0'],generateHighQualityLinkPreview:false});
 sock.ev.on('creds.update',saveCreds); sock.ev.on('connection.update',async u=>{ const {connection,lastDisconnect,qr}=u; if(qr){state.qr=await QRCode.toDataURL(qr);state.status='qr-ready';} if(connection==='open'){state={...state,status:'connected',qr:null,lastError:null};logger.info({user:sock.user?.id},'WhatsApp connected');} if(connection==='close'){const code=new Boom(lastDisconnect?.error)?.output?.statusCode; state.status=code===DisconnectReason.loggedOut?'logged-out':'reconnecting'; sock=null; starting=false; if(code!==DisconnectReason.loggedOut) setTimeout(startConnection,3000);}}); starting=false; return sock; }
export async function requestPairing(number){ if(!sock) await startConnection(); if(sock?.authState?.creds?.registered) throw new Error('Already registered'); const digits=String(number).replace(/\D/g,''); if(digits.length<8) throw new Error('Enter a valid international phone number'); state.pairingCode=await sock.requestPairingCode(digits); state.status='pairing-code-ready'; return state.pairingCode; }
export async function stopConnection(){ if(sock){ try{sock.end(undefined);}catch{} sock=null; } state.status='stopped'; }
export const getSocket=()=>sock;
